import { unstable_getServerSession } from "next-auth/next"
import { useSession } from "next-auth/react"
import { prisma } from "../src/prisma"

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Layout from '../src/components/layout'
import Places from "../src/components/crosswalkForm"
import { authOptions } from "./api/auth/[...nextauth]"

const inter = Inter({ subsets: ['latin'] })

export default function Home({ markers }) {
  const { data: session, status } = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout 
      main={        
        <div>
          <Places markers={markers} session={session}/>
        </div>
      }/>
    </>
  )
}

export async function getServerSideProps(context) {
  const session = await unstable_getServerSession(context.req, context.res, authOptions)

  const allCrosswalks = await prisma.crosswalk.findMany();
  console.log(allCrosswalks)
  const markers = []
  return {
    props: {
      session,
      markers
    },
  }
}